subscription_id     = "ef3ac21e-bc8a-4281-848b-3e98aab8f89e"
location            = "North Europe"
customer            = "intern"
environment         = "dev"
api_key             = "xejbndlhntftpljr"
predict_backend_base_url = "https://app-count-intern-dev-predictions.azurewebsites.net/api/v1"
predict_backend_api_key = "e5h1si8l0n6x"