name: 'COUNT INTERN PRD Backend Deployment'

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_INTERN_PRD }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_INTERN_PRD }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_INTERN_PRD }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_INTERN_PRD }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0
      
    - working-directory: terraform
      run: terraform init --backend-config="environment/intern/prd/backend.conf"
      
    - working-directory: terraform
      run: terraform apply --var-file="environment/intern/prd/terraform.tfvars" -auto-approve

  docker:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    needs: terraform

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER_INTERN_PRD }}
          username: ${{ secrets.ACR_USERNAME_INTERN_PRD }}
          password: ${{ secrets.ACR_PASSWORD_INTERN_PRD }}

      - uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER_INTERN_PRD }}/count-intern-prd-backend:latest

      - run: sleep 60

      - run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID_INTERN_PRD }} -p ${{ secrets.AZURE_CLIENT_SECRET_INTERN_PRD}} --tenant ${{ secrets.AZURE_TENANT_ID_INTERN_PRD }}
          az webapp restart --name app-count-intern-prd-backend --resource-group rg-count-intern-prd-apps
